import hashlib
import os

import streamlit as st
from passlib.hash import pbkdf2_sha256
import psycopg
from supabase import create_client


# Areas de atuacao (filtro PRIMARIO de acesso por relatorio).
CATEGORIAS_PADRAO = [
    "GERAL",
    "FINANCEIRO",
    "SUPRIMENTOS",
    "INSUMOS",
    "MARKETING",
    "OPERACIONAL",
    "SOLINFITEC",
    "LOGISTICA",
    "VENDAS",
    "DIRETORIA",
    "RH",
    "CONTROLADORIA",
]

# Hierarquia de acesso. 'gestao' enxerga relatorios de gestao E de operacao;
# 'operacao' enxerga apenas relatorios de operacao.
NIVEIS_HIERARQUIA = ["gestao", "operacao"]
NIVEL_LABELS = {"gestao": "Gestão", "operacao": "Operação"}
NIVEL_PADRAO = "operacao"

# Mapeamento de categorias antigas -> novas (migracao automatica de dados).
_MAPA_CATEGORIAS_LEGADO = {
    "Geral": "GERAL",
    "Vendas": "VENDAS",
    "Marketing": "MARKETING",
    "Financeiro": "FINANCEIRO",
    "RH": "RH",
    "Operacoes": "OPERACIONAL",
    "Operações": "OPERACIONAL",
    "Logistica": "LOGISTICA",
    "Logística": "LOGISTICA",
    "Suprimentos": "SUPRIMENTOS",
    "Operacional": "OPERACIONAL",
}


def normalizar_nivel(valor):
    valor = (valor or "").strip().lower()
    return valor if valor in NIVEIS_HIERARQUIA else NIVEL_PADRAO


class Database:
    _COLS_RELATORIO = (
        "id,titulo,link_powerbi,descricao,categoria,nivel_hierarquia,"
        "criado_por,criado_em,atualizado_em"
    )

    def __init__(self):
        self.supabase = self._create_client()
        self.init_database()

    # ----------------------------------------------------------------- infra
    def _get_secret(self, key: str, default: str = "") -> str:
        if key in st.secrets:
            return str(st.secrets[key])
        return os.getenv(key, default)

    def _create_client(self):
        url = self._get_secret("SUPABASE_URL")
        key = self._get_secret("SUPABASE_KEY")
        if not url or not key:
            raise RuntimeError("SUPABASE_URL e SUPABASE_KEY sao obrigatorios.")
        return create_client(url, key)

    def _create_schema_if_needed(self):
        db_url = self._get_secret("SUPABASE_DB_URL")
        if not db_url:
            raise RuntimeError(
                "Schema/colunas ausentes no Supabase e SUPABASE_DB_URL nao foi "
                "definido para criacao/migracao automatica. Rode supabase_schema.sql "
                "ou migration_v3.sql no SQL Editor."
            )

        schema_sql = """
        create table if not exists public.usuarios (
            id bigint generated by default as identity primary key,
            username text unique not null,
            email text unique,
            password_hash text not null,
            is_admin boolean not null default false,
            ativo boolean not null default true,
            nivel_hierarquia text not null default 'operacao',
            categorias_permitidas jsonb not null default '[]'::jsonb,
            relatorios_permitidos jsonb not null default '[]'::jsonb,
            criado_em timestamptz not null default now()
        );

        create table if not exists public.relatorios (
            id bigint generated by default as identity primary key,
            titulo text not null,
            link_powerbi text not null,
            descricao text,
            categoria text not null default 'GERAL',
            nivel_hierarquia text not null default 'operacao',
            tags text,
            criado_por bigint references public.usuarios(id) on delete set null,
            ativo boolean not null default true,
            criado_em timestamptz not null default now(),
            atualizado_em timestamptz not null default now()
        );

        create table if not exists public.logs_acesso (
            id bigint generated by default as identity primary key,
            usuario_id bigint references public.usuarios(id) on delete set null,
            relatorio_id bigint references public.relatorios(id) on delete set null,
            data_acesso timestamptz not null default now()
        );

        -- Migracao de bases existentes: adiciona colunas novas se faltarem.
        alter table public.usuarios
            add column if not exists nivel_hierarquia text not null default 'operacao';
        alter table public.usuarios
            add column if not exists relatorios_permitidos jsonb not null default '[]'::jsonb;
        alter table public.relatorios
            add column if not exists nivel_hierarquia text not null default 'operacao';

        create index if not exists idx_relatorios_categoria on public.relatorios(categoria);
        create index if not exists idx_relatorios_nivel on public.relatorios(nivel_hierarquia);
        create index if not exists idx_relatorios_criado_por on public.relatorios(criado_por);
        create index if not exists idx_usuarios_username on public.usuarios(username);

        create or replace function public.set_relatorio_updated_at()
        returns trigger
        language plpgsql
        as $$
        begin
            new.atualizado_em = now();
            return new;
        end;
        $$;

        drop trigger if exists trg_relatorios_updated_at on public.relatorios;
        create trigger trg_relatorios_updated_at
        before update on public.relatorios
        for each row
        execute function public.set_relatorio_updated_at();

        alter table public.usuarios disable row level security;
        alter table public.relatorios disable row level security;
        """

        with psycopg.connect(db_url, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(schema_sql)

    # ---------------------------------------------------------------- senhas
    def hash_password(self, password: str) -> str:
        return pbkdf2_sha256.hash(password)

    @staticmethod
    def _legacy_hash_password(password: str) -> str:
        # Compatibilidade com hashes antigos (sha256 + salt fixo).
        return hashlib.sha256(f"{password}_salt_grupofrt".encode()).hexdigest()

    def _verify_password(self, password: str, stored_hash: str):
        # Tenta verificar hash moderno (pbkdf2_sha256).
        try:
            if stored_hash and stored_hash.startswith("$pbkdf2-sha256$"):
                return pbkdf2_sha256.verify(password, stored_hash), False
        except Exception:
            pass

        # Fallback para hash legado.
        if self._legacy_hash_password(password) == stored_hash:
            return True, True

        return False, False

    # -------------------------------------------------------- normalizacao
    @staticmethod
    def _parse_categorias(value, is_admin=False):
        if isinstance(value, list):
            return value
        return CATEGORIAS_PADRAO if is_admin else []

    @staticmethod
    def _parse_relatorios_permitidos(value):
        if not isinstance(value, list):
            return []
        ids = []
        for v in value:
            try:
                ids.append(int(v))
            except (TypeError, ValueError):
                continue
        return ids

    @staticmethod
    def _hierarquia_ok(nivel_usuario, nivel_relatorio):
        # gestao enxerga gestao + operacao; operacao so enxerga operacao.
        if normalizar_nivel(nivel_usuario) == "gestao":
            return True
        return normalizar_nivel(nivel_relatorio) == "operacao"

    def _pode_ver_relatorio(self, usuario, r):
        """Regra de visibilidade de um relatorio (linha crua do banco) para um usuario.

        Nao-admin enxerga se, ao mesmo tempo:
          - a area (categoria) esta entre as suas areas permitidas (filtro primario);
          - a hierarquia do relatorio e compativel com o nivel do usuario;
          - e, se houver liberacao individual definida, o relatorio esta na lista
            (filtro secundario restritivo).
        O criador sempre acessa o proprio relatorio (para editar/visualizar).
        """
        if usuario.get("is_admin"):
            return True
        if r.get("criado_por") is not None and r.get("criado_por") == usuario.get("id"):
            return True

        areas = usuario.get("categorias_permitidas") or []
        if (r.get("categoria") or "GERAL") not in areas:
            return False
        if not self._hierarquia_ok(usuario.get("nivel_hierarquia"), r.get("nivel_hierarquia")):
            return False
        permitidos = usuario.get("relatorios_permitidos") or []
        if permitidos and r.get("id") not in permitidos:
            return False
        return True

    # ------------------------------------------------------------ init/seed
    def _smoke_test_schema(self):
        # Falha se as colunas novas ainda nao existirem -> dispara a migracao.
        self.supabase.table("usuarios").select(
            "id,nivel_hierarquia,relatorios_permitidos"
        ).limit(1).execute()
        self.supabase.table("relatorios").select("id,nivel_hierarquia").limit(1).execute()

    def init_database(self):
        try:
            self._smoke_test_schema()
        except Exception:
            self._create_schema_if_needed()
            self._smoke_test_schema()

        self._garantir_admin()
        self._migrar_categorias_legado()
        self._backfill_padroes()

    def _garantir_admin(self):
        admin = (
            self.supabase.table("usuarios")
            .select("id")
            .eq("username", "admin")
            .limit(1)
            .execute()
        )
        if not admin.data:
            initial_admin_password = self._get_secret("ADMIN_INITIAL_PASSWORD")
            if not initial_admin_password:
                raise RuntimeError(
                    "Usuario admin nao existe e ADMIN_INITIAL_PASSWORD nao foi definido."
                )
            self.supabase.table("usuarios").insert(
                {
                    "username": "admin",
                    "password_hash": self.hash_password(initial_admin_password),
                    "is_admin": True,
                    "nivel_hierarquia": "gestao",
                    "categorias_permitidas": CATEGORIAS_PADRAO,
                    "relatorios_permitidos": [],
                }
            ).execute()

    def _migrar_categorias_legado(self):
        # Remapeia categorias antigas dos relatorios para as novas (maiusculas).
        # Idempotente: apos a migracao nao ha mais valores legados.
        for antigo, novo in _MAPA_CATEGORIAS_LEGADO.items():
            if antigo == novo:
                continue
            achou = (
                self.supabase.table("relatorios")
                .select("id")
                .eq("categoria", antigo)
                .limit(1)
                .execute()
            )
            if achou.data:
                (
                    self.supabase.table("relatorios")
                    .update({"categoria": novo})
                    .eq("categoria", antigo)
                    .execute()
                )

    def _backfill_padroes(self):
        users = (
            self.supabase.table("usuarios")
            .select("id,is_admin,categorias_permitidas")
            .execute()
        )
        for user in users.data or []:
            cats = user.get("categorias_permitidas")
            novas = None
            if isinstance(cats, list) and cats:
                # Remapeia categorias antigas e descarta as que nao existem mais,
                # preservando a ordem padrao.
                convertidas = {_MAPA_CATEGORIAS_LEGADO.get(c, c) for c in cats}
                convertidas = [c for c in CATEGORIAS_PADRAO if c in convertidas]
                if convertidas != cats:
                    novas = convertidas or (["GERAL"] if not user.get("is_admin") else CATEGORIAS_PADRAO)
            elif not cats:
                novas = CATEGORIAS_PADRAO if user.get("is_admin") else ["GERAL"]
            if novas is not None:
                (
                    self.supabase.table("usuarios")
                    .update({"categorias_permitidas": novas})
                    .eq("id", user["id"])
                    .execute()
                )

    # ----------------------------------------------------------------- auth
    def autenticar_usuario(self, username: str, password: str):
        resp = (
            self.supabase.table("usuarios")
            .select(
                "id,username,password_hash,is_admin,nivel_hierarquia,"
                "categorias_permitidas,relatorios_permitidos"
            )
            .eq("username", username)
            .limit(1)
            .execute()
        )
        if not resp.data:
            return None

        usuario = resp.data[0]
        password_ok, needs_rehash = self._verify_password(password, usuario["password_hash"])
        if not password_ok:
            return None

        if needs_rehash:
            (
                self.supabase.table("usuarios")
                .update({"password_hash": self.hash_password(password)})
                .eq("id", usuario["id"])
                .execute()
            )

        is_admin = bool(usuario.get("is_admin", False))
        return {
            "id": usuario["id"],
            "username": usuario["username"],
            "is_admin": is_admin,
            "nivel_hierarquia": normalizar_nivel(usuario.get("nivel_hierarquia")),
            "categorias_permitidas": self._parse_categorias(
                usuario.get("categorias_permitidas"), is_admin
            ),
            "relatorios_permitidos": self._parse_relatorios_permitidos(
                usuario.get("relatorios_permitidos")
            ),
            "autenticado": True,
        }

    # ------------------------------------------------------------ relatorios
    def _usuarios_map_por_id(self):
        resp = self.supabase.table("usuarios").select("id,username").execute()
        return {u["id"]: u["username"] for u in (resp.data or [])}

    def _montar_relatorio(self, r, user_map):
        return {
            "id": r["id"],
            "titulo": r["titulo"],
            "link_powerbi": r["link_powerbi"],
            "descricao": r.get("descricao"),
            "categoria": r.get("categoria") or "GERAL",
            "nivel_hierarquia": normalizar_nivel(r.get("nivel_hierarquia")),
            "criado_por": r.get("criado_por"),
            "criado_em": r.get("criado_em"),
            "atualizado_em": r.get("atualizado_em") or r.get("criado_em"),
            "criador": user_map.get(r.get("criado_por"), "Sistema"),
        }

    def listar_relatorios_usuario(self, usuario):
        query = (
            self.supabase.table("relatorios")
            .select(self._COLS_RELATORIO)
            .order("criado_em", desc=True)
        )
        if not usuario["is_admin"]:
            areas = usuario.get("categorias_permitidas") or []
            if not areas:
                return []
            query = query.in_("categoria", areas)

        resp = query.execute()
        user_map = self._usuarios_map_por_id()
        permitidos = set(usuario.get("relatorios_permitidos") or [])
        nivel_user = usuario.get("nivel_hierarquia")

        relatorios = []
        for r in resp.data or []:
            if not usuario["is_admin"]:
                if not self._hierarquia_ok(nivel_user, r.get("nivel_hierarquia")):
                    continue
                if permitidos and r["id"] not in permitidos:
                    continue
            relatorios.append(self._montar_relatorio(r, user_map))
        return relatorios

    def obter_relatorio_por_id(self, relatorio_id, usuario=None):
        resp = (
            self.supabase.table("relatorios")
            .select(self._COLS_RELATORIO)
            .eq("id", relatorio_id)
            .limit(1)
            .execute()
        )
        if not resp.data:
            return None
        r = resp.data[0]
        # Defesa em profundidade: so devolve se o usuario tiver permissao de ver.
        if usuario is not None and not self._pode_ver_relatorio(usuario, r):
            return None
        return self._montar_relatorio(r, self._usuarios_map_por_id())

    def listar_relatorios_basico(self):
        # Lista enxuta (id/titulo/categoria/nivel) para o multiselect de
        # liberacao individual na gestao de usuarios.
        resp = (
            self.supabase.table("relatorios")
            .select("id,titulo,categoria,nivel_hierarquia")
            .execute()
        )
        rows = [
            {
                "id": r["id"],
                "titulo": r["titulo"],
                "categoria": r.get("categoria") or "GERAL",
                "nivel_hierarquia": normalizar_nivel(r.get("nivel_hierarquia")),
            }
            for r in (resp.data or [])
        ]
        rows.sort(key=lambda r: (r["categoria"], r["titulo"].lower()))
        return rows

    def criar_relatorio(self, titulo, link_powerbi, descricao, categoria, criado_por,
                        nivel_hierarquia="operacao"):
        self.supabase.table("relatorios").insert(
            {
                "titulo": titulo,
                "link_powerbi": link_powerbi,
                "descricao": descricao,
                "categoria": categoria,
                "nivel_hierarquia": normalizar_nivel(nivel_hierarquia),
                "criado_por": criado_por,
            }
        ).execute()
        return True

    def atualizar_relatorio(self, relatorio_id, titulo, link_powerbi, descricao, categoria,
                           nivel_hierarquia="operacao"):
        (
            self.supabase.table("relatorios")
            .update(
                {
                    "titulo": titulo,
                    "link_powerbi": link_powerbi,
                    "descricao": descricao,
                    "categoria": categoria,
                    "nivel_hierarquia": normalizar_nivel(nivel_hierarquia),
                }
            )
            .eq("id", relatorio_id)
            .execute()
        )
        return True

    def excluir_relatorio(self, relatorio_id):
        self.supabase.table("relatorios").delete().eq("id", relatorio_id).execute()
        return True

    # -------------------------------------------------------------- usuarios
    def listar_usuarios(self):
        resp = (
            self.supabase.table("usuarios")
            .select(
                "id,username,is_admin,nivel_hierarquia,"
                "categorias_permitidas,relatorios_permitidos,criado_em"
            )
            .order("criado_em", desc=True)
            .execute()
        )
        usuarios = []
        for u in resp.data or []:
            is_admin = bool(u.get("is_admin", False))
            usuarios.append(
                {
                    "id": u["id"],
                    "username": u["username"],
                    "is_admin": is_admin,
                    "nivel_hierarquia": normalizar_nivel(u.get("nivel_hierarquia")),
                    "categorias_permitidas": self._parse_categorias(
                        u.get("categorias_permitidas"), is_admin
                    ),
                    "relatorios_permitidos": self._parse_relatorios_permitidos(
                        u.get("relatorios_permitidos")
                    ),
                    "criado_em": u.get("criado_em"),
                }
            )
        return usuarios

    def obter_usuario_por_id(self, usuario_id):
        resp = (
            self.supabase.table("usuarios")
            .select(
                "id,username,is_admin,nivel_hierarquia,"
                "categorias_permitidas,relatorios_permitidos"
            )
            .eq("id", usuario_id)
            .limit(1)
            .execute()
        )
        if not resp.data:
            return None
        u = resp.data[0]
        is_admin = bool(u.get("is_admin", False))
        return {
            "id": u["id"],
            "username": u["username"],
            "is_admin": is_admin,
            "nivel_hierarquia": normalizar_nivel(u.get("nivel_hierarquia")),
            "categorias_permitidas": self._parse_categorias(
                u.get("categorias_permitidas"), is_admin
            ),
            "relatorios_permitidos": self._parse_relatorios_permitidos(
                u.get("relatorios_permitidos")
            ),
        }

    def criar_usuario_portal(self, username, senha, is_admin=False, nivel_hierarquia="operacao",
                            categorias_permitidas=None, relatorios_permitidos=None):
        if is_admin:
            # Admin enxerga tudo; os filtros sao normalizados.
            nivel_hierarquia = "gestao"
            categorias_permitidas = CATEGORIAS_PADRAO
            relatorios_permitidos = []
        else:
            if categorias_permitidas is None:
                categorias_permitidas = ["GERAL"]
            relatorios_permitidos = self._parse_relatorios_permitidos(relatorios_permitidos or [])

        self.supabase.table("usuarios").insert(
            {
                "username": username,
                "password_hash": self.hash_password(senha),
                "is_admin": bool(is_admin),
                "nivel_hierarquia": normalizar_nivel(nivel_hierarquia),
                "categorias_permitidas": categorias_permitidas,
                "relatorios_permitidos": relatorios_permitidos,
            }
        ).execute()
        return True

    def atualizar_usuario_portal(self, usuario_id, username=None, is_admin=None,
                                nivel_hierarquia=None, categorias_permitidas=None,
                                relatorios_permitidos=None):
        updates = {}
        if username:
            updates["username"] = username

        if is_admin is True:
            # Promovido a admin: enxerga tudo, zera filtros granulares.
            updates["is_admin"] = True
            updates["nivel_hierarquia"] = "gestao"
            updates["categorias_permitidas"] = CATEGORIAS_PADRAO
            updates["relatorios_permitidos"] = []
        else:
            if is_admin is False:
                updates["is_admin"] = False
            if nivel_hierarquia is not None:
                updates["nivel_hierarquia"] = normalizar_nivel(nivel_hierarquia)
            if categorias_permitidas is not None:
                updates["categorias_permitidas"] = categorias_permitidas
            if relatorios_permitidos is not None:
                updates["relatorios_permitidos"] = self._parse_relatorios_permitidos(
                    relatorios_permitidos
                )

        if not updates:
            return True
        self.supabase.table("usuarios").update(updates).eq("id", usuario_id).execute()
        return True

    def atualizar_senha_portal(self, usuario_id, nova_senha):
        (
            self.supabase.table("usuarios")
            .update({"password_hash": self.hash_password(nova_senha)})
            .eq("id", usuario_id)
            .execute()
        )
        return True

    def excluir_usuario(self, usuario_id):
        self.supabase.table("usuarios").delete().eq("id", usuario_id).execute()
        return True
