-- Execute este script no SQL Editor do Supabase (instalacao nova).
-- Para uma base que ja existe (v2), use migration_v3.sql.

create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    username text unique not null,
    email text unique,
    password_hash text not null,
    is_admin boolean not null default false,
    ativo boolean not null default true,
    -- Hierarquia de acesso: 'gestao' enxerga gestao + operacao; 'operacao' so operacao.
    nivel_hierarquia text not null default 'operacao',
    -- Filtro primario: areas de atuacao que o usuario pode acessar.
    categorias_permitidas jsonb not null default '[]'::jsonb,
    -- Filtro secundario (restritivo): se preenchido, o usuario ve APENAS estes
    -- relatorios (dentro das areas/nivel permitidos). Vazio = todos da area.
    relatorios_permitidos jsonb not null default '[]'::jsonb,
    criado_em timestamptz not null default now()
);

create table if not exists public.relatorios (
    id bigint generated by default as identity primary key,
    titulo text not null,
    link_powerbi text not null,
    descricao text,
    categoria text not null default 'GERAL',
    -- Hierarquia do relatorio: 'gestao' ou 'operacao'.
    nivel_hierarquia text not null default 'operacao',
    tags text,
    criado_por bigint references public.usuarios(id) on delete set null,
    ativo boolean not null default true,
    criado_em timestamptz not null default now(),
    atualizado_em timestamptz not null default now()
);

create table if not exists public.logs_acesso (
    id bigint generated by default as identity primary key,
    usuario_id bigint references public.usuarios(id) on delete set null,
    relatorio_id bigint references public.relatorios(id) on delete set null,
    data_acesso timestamptz not null default now()
);

create index if not exists idx_relatorios_categoria on public.relatorios(categoria);
create index if not exists idx_relatorios_nivel on public.relatorios(nivel_hierarquia);
create index if not exists idx_relatorios_criado_por on public.relatorios(criado_por);
create index if not exists idx_usuarios_username on public.usuarios(username);

-- Atualiza atualizado_em automaticamente.
create or replace function public.set_relatorio_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.atualizado_em = now();
    return new;
end;
$$;

drop trigger if exists trg_relatorios_updated_at on public.relatorios;
create trigger trg_relatorios_updated_at
before update on public.relatorios
for each row
execute function public.set_relatorio_updated_at();

-- Para ambientes internos simples, voce pode manter RLS desativado.
-- Se quiser habilitar RLS, crie policies para leitura/escrita com service role
-- ou via autenticacao do Supabase Auth.
alter table public.usuarios disable row level security;
alter table public.relatorios disable row level security;
